train:
  number_of_problems_per_batch: 16
  num_samples_per_problem: 8

  learning_rate: 5e-7
  beta: 0.001
  mu: 2

teacher_model:
  model_name_or_path: Qwen/Qwen2.5-7B-Instruct
  vllm:
    temperature: 1.0
    max_length: 12000
    max_num_seqs: 512
    gpu_memory_utilization: 0.325
    number_of_gpus_per_instance: 4
    max_number_of_instances: -1
    load_and_unload: true
    use_v0: true
    enforce_eager: true

student_model:
  model_name_or_path: neuralmagic/Meta-Llama-3.1-8B-Instruct-FP8
  vllm:
    temperature: 0.6
    max_length: 12000
    max_num_seqs: 512
    gpu_memory_utilization: 0.325
    number_of_gpus_per_instance: 4
    max_number_of_instances: -1
    use_v0: false

    load_and_unload: true

judge_model:
  model_name_or_path: Qwen/Qwen2.5-14B-Instruct-AWQ
  vllm:
    temperature: 0.6
    max_length: 12000
    max_num_seqs: 512
    gpu_memory_utilization: 0.325
    number_of_gpus_per_instance: 4
    max_number_of_instances: -1
    load_and_unload: false
    use_v0: false

reward_model:
  model_name_or_path: Answer # If we set this to None we get the -r_sol run.

huggingface:
  name: <huggingface_name>
  push_to_hub: false

logging:
  wandb: true
  wandb_project: train-rl
  wandb_run_name: Qwen2.5-7B-Instruct-HardLambda1.0
  run_group: 7b
  wandb_tags: ["7b"]
  save_dir: checkpoints/7b
  save_steps: 10


generation:

  # This turns on thinking.
  # use_thinking: true
  # force_thinking: true

  # This turns on the hard lambda.
  extra_penalty_for_rejected_judges: 1.0 # This is the actual lambda we use.
  ignore_penalty_for_rejected_judges: false # If we set this to false we get the soft lambda runs.

  use_experimental_shared_memory: false
  
  # If we turn this on we get the lambda=0.0 run
  # number_judge_attempts: 0
  # judges_rules_prompts_paths: {}