teacher_model:
  model_name_or_path: Qwen/Qwen2.5-7B-Instruct
  use_openrouter: false
  vllm:
    temperature: 0.6
    max_length: 12000
    max_num_seqs: 512
    gpu_memory_utilization: 0.7
    number_of_gpus_per_instance: 1
    enforce_eager: true

student_model:
  model_name_or_path: neuralmagic/Meta-Llama-3.1-8B-Instruct-FP8
  vllm:
    temperature: 0.6
    max_length: 12000
    max_num_seqs: 512
    gpu_memory_utilization: 0.7
    number_of_gpus_per_instance: 1
    enforce_eager: true

judge_model:
  model_name_or_path: gpt-4.1-mini
  use_openrouter: false
  use_openai: true
  vllm:
    temperature: 0.6

reward_model:
  model_name_or_path: "Answer"

logging:
  wandb: true
  wandb_project: eval
  wandb_run_name: GPT-4.1mini-Judge
  run_group: gpt4.1mini-judge
  wandb_tags: ["gpt4.1mini-judge", "openai", "7b"] 