teacher_model:
  model_name_or_path: CogBase-USTC/SocraticLM
  use_openrouter: false
  vllm:
    temperature: 0.6
    max_length: 4096
    max_num_seqs: 512
    gpu_memory_utilization: 0.85
    number_of_gpus_per_instance: 1
    enforce_eager: true

student_model:
  model_name_or_path: neuralmagic/Meta-Llama-3.1-8B-Instruct-FP8
  vllm:
    temperature: 0.6
    max_length: 12000
    max_num_seqs: 512
    gpu_memory_utilization: 0.85
    number_of_gpus_per_instance: 1
    enforce_eager: true
    
judge_model:
  model_name_or_path: google/gemma-3-27b-it
  vllm:
    temperature: 0.6
    max_length: 12000
    max_num_seqs: 512
    gpu_memory_utilization: 0.85
    number_of_gpus_per_instance: 1
    enforce_eager: true

reward_model:
  model_name_or_path: "Answer"

generation:
  teacher_prompt_path: "prompt_templates/socracticlm/socracticlm_teacher_prompt.txt"

logging:
  wandb: true
  wandb_project: eval
  wandb_run_name: SocraticLM
  run_group: tutor
  wandb_tags: ["tutor", "7b"]
